language: node_js
node_js:
  - '8'
env:
  - RCLONE_VERSION="1.37"
script:
  - npm run clean
  - npm run build
deploy:
  skip_cleanup: true
  provider: script
  script: ./rclone-deploy.sh
  on:
    branch: master
